### ISSUE TITLE
Table 2

### ISSUE THREAD

**Issue by wjczf123** [thunlp/DecT#2]
Hi, ganqu. Do the results of Table 2 run on SST2 dataset?

**Comment by wjczf123** [comment]
Hi, ganqu. Can you provide the detailed results in Figure 1? 
Thanks. I am looking forward to your reply.

**Comment by cgq15** [comment]
> Hi, ganqu. Do the results of Table 2 run on SST2 dataset?

The results are averaged on all datasets we use

**Comment by cgq15** [comment]
> Hi, ganqu. Can you provide the detailed results in Figure 1? Thanks. I am looking forward to your reply.

The data points are from Table 1, 2 and 3, could you figure out which data point you are interested in?

**Comment by wjczf123** [comment]
Thanks for your reply. I have got training time in Figure 1. Thanks.
